class StringConstants:
    COMMON_PREFIX: str = 'api/inference'
    DOCUMENT_PATH_KEY: str = 'documentPath'
    DOOR_TYPE_KEY: str = 'doorType'
    DOOR_KEY: str = 'door'
    END_KEY: str = 'end'
    EXECUTABLE_PARAMS_KEY: str = 'executable_params'
    FILE_URL_KEY: str = 'fileUrl'
    FLOOR_ID_KEY: str = 'floor'
    HOTSPOT_RESULT_KEY: str = 'hotspot_result'
    HOTSPOT_INFO_KEY: str = 'hot_spot_info'
    INFERENCE_ID_KEY: str = 'inferenceId'
    INPUT_PATH_KEY = 'input_path'
    IMAGE_PATH_KEY: str = "imagePath"
    LAYOUT_KEY: str = 'layout'
    MERGED_IMG_PATH: str = 'merged_image_path'
    MESSAGE_TYPE_KEY: str = 'messageType'
    ORDER_ID_KEY: str = 'orderId'
    OUTPUT_PATH_KEY = 'output_path'
    PANOS_KEY: str = 'panos'
    PANO_ID_KEY: str = 'panoId'
    PANO_URL_KEY: str = 'panoUrl'
    PATH_DIRECTION_KEY: str = 'pathDirection'
    PATH_CORNER_KEY: str = 'pathCorner'
    PRY_MATRIX_KEY: str = 'pry'
    RESULT_FILE_NAME: str = 'result.json'
    ROOM_KEY: str = 'room'
    START_KEY: str = 'start'
    STEPS_DOCUMENT_PATH_KEY: str = "stepsDocumentPath"
    STEPS_KEY: str = 'steps'
    TOUR_ID_KEY: str = 'tourId'
    TYPE_KEY: str = 'type'
    VISUAL_PROB_KEY: str = 'visual_probability'
    TO_KEY: str = 'to'


